### ISSUE TITLE
inventory issuse

### ISSUE THREAD

**Issue by MettyOwO** [Stella2Aurora/Raycity#4]
Hi, I've been testing game it for a while now.
i have a problem with item and setitem admin command. 
when using this command, items don't add directly to inventory.
must have go to shop and buy someitem, so item is appear but stack error.
I must drag item. can guide me how to fix it?
PS. i don't understand some inventorydb.
PS2. [Set5] Wolf Brave Warrior Decal how to fix game crash? i try to change another EquipID but still same.
Sorry for bad English.

**Comment by imhatepython** [comment]
USE [GameDB00]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[FN_AddItemToUser]
	@in_CharacterID int,
	@in_CarInventoryIDX int,
	@in_InventoryCellNo int,
	@in_ItemID int,
	@in_ExpDays INT
AS
BEGIN
declare @EXpDate datetime
		declare @CurDate datetime = GETDATE ()

		IF (@in_ExpDays = 7)
		BEGIN
				set @EXpDate = DATEADD(day, 7, @CurDate)
		END
		ELSE IF (@in_ExpDays = 30) BEGIN
		set @EXpDate = DATEADD(day, 30, @CurDate)
		END

	
	
		declare @in_ExpDays1 int 
		if(@in_ExpDays = 7) BEGIN
			SET @in_ExpDays1 = 0;
		END
		ELSE IF (@in_ExpDays = 30) BEGIN
			SET @in_ExpDays1 = 0;
		END
		ELSE IF (@in_ExpDays = 0) BEGIN
			SET @in_ExpDays1 = 10;
		END
	



	INSERT INTO GameDB00.dbo.RC_GetInventoryItem ( 
			CharacterID,
			CarInventoryIDX,
			InventoryCellNo,
			ItemIDX,
			ItemID,
			MaxEndurance,
			CurEndurance,
			Duration,
			ItemOption1,
			ItemOption2,
			ItemOption3,
			Bonding
	
		) VALUES (
			@in_CharacterID,
			@in_CarInventoryIDX,
			@in_InventoryCellNo,
			0,
			@in_ItemID,
			10000,
			10000,
			@in_ExpDays1,
			0,
			0,
			0,
			0
				
		)

		declare @InventoryIDX_ int = SCOPE_IDENTITY()

		update  GameDB00.dbo.RC_GetInventoryItem set ItemIDX = @InventoryIDX_ where InventoryItemIDX=@InventoryIDX_
		
END

**Comment by imhatepython** [comment]
The problem with Wolf Brave Warrior Decal is the failure to import Decal4.jmd files from the client

590 uses only Decal1~3
It will probably require a bit of client modification to use
